# -*- coding: utf-8 -*-
"""Age_Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sMcClamgih2w-_rbcG1JWU16v_Fpz1fg
"""

from datetime import datetime

def calculate_age(birth_date):
    today = datetime.today()
    age = today.year - birth_date.year

    # Adjust age if birthday has not occurred yet this year
    if (today.month, today.day) < (birth_date.month, birth_date.day):
        age -= 1

    return age

try:
    # Ask user for birth date
    user_input = input("Enter your birth date (mm/dd/yyyy): ")

    # Validate format and date
    birth_date = datetime.strptime(user_input, "%m/%d/%Y")

    # Calculate age
    age = calculate_age(birth_date)

    # Convert to European format
    european_format = birth_date.strftime("%d/%m/%Y")

    # Display results
    print("\n--- Results ---")
    print(f"Valid Birth Date : {user_input}")
    print(f"Age              : {age} years")
    print(f"European Format  : {european_format}")

except ValueError:
    # Handle invalid date or format
    print("\nError: Invalid date format or invalid calendar date.")
    print("Please enter the date in mm/dd/yyyy format (e.g., 08/15/2001).")

except Exception as e:
    # Catch any unexpected errors
    print("\nAn unexpected error occurred.")
    print(f"Details: {e}")