# -*- coding: utf-8 -*-
"""Fetch_WeatherData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xEwwSWLQCkOWjBJ-ym0CmrSayXdmVn7m
"""

pip install requests

import requests
import csv
from datetime import datetime


def fetch_weather(city: str, api_key: str) -> dict:
    """
    Fetches weather data for a given city using OpenWeatherMap API.
    """
    url = (
        "https://api.openweathermap.org/data/2.5/weather"
        f"?q={city}&appid={api_key}&units=metric"
    )

    try:
        response = requests.get(url, timeout=10)
        response.raise_for_status()
        return response.json()

    except requests.exceptions.HTTPError:
        print(f"❌ Error: City '{city}' not found or invalid API key.")
    except requests.exceptions.ConnectionError:
        print("❌ Error: Network connection issue.")
    except requests.exceptions.Timeout:
        print("❌ Error: Request timed out.")
    except requests.exceptions.RequestException as e:
        print(f"❌ Unexpected error: {e}")

    return {}


def analyze_weather(weather_data: dict) -> str:
    """
    Analyzes weather data and returns insights.
    """
    try:
        temp = weather_data["main"]["temp"]
        humidity = weather_data["main"]["humidity"]
        wind_speed = weather_data["wind"]["speed"]

        insights = []

        # Temperature classification
        if temp <= 10:
            insights.append("Cold (≤10°C)")
        elif 11 <= temp <= 24:
            insights.append("Mild (11–24°C)")
        else:
            insights.append("Hot (≥25°C)")

        # Warnings
        if wind_speed > 10:
            insights.append("High wind alert!")
        if humidity > 80:
            insights.append("Humid conditions!")

        return " | ".join(insights)

    except KeyError:
        return "Weather data incomplete."


def log_weather(city: str, filename: str, api_key: str):
    """
    Fetches weather data and appends it to a CSV file.
    """
    data = fetch_weather(city, api_key)
    if not data:
        return

    try:
        temp = data["main"]["temp"]
        humidity = data["main"]["humidity"]
        wind_speed = data["wind"]["speed"]
        description = data["weather"][0]["description"]
        summary = analyze_weather(data)
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        with open(filename, mode="a", newline="") as file:
            writer = csv.writer(file)

            # Write header if file is empty
            if file.tell() == 0:
                writer.writerow([
                    "Timestamp",
                    "City",
                    "Temperature (°C)",
                    "Humidity (%)",
                    "Wind Speed (m/s)",
                    "Description",
                    "Insights"
                ])

            writer.writerow([
                timestamp,
                city,
                temp,
                humidity,
                wind_speed,
                description,
                summary
            ])

        print(f"✅ Weather data for '{city}' logged successfully.")
        print(f"Insights: {summary}")

    except Exception as e:
        print(f"❌ Error while writing to file: {e}")


# MAIN EXECUTION

if __name__ == "__main__":
    API_KEY = "3b4ec62bdd23e9ca8f5862165838e815"
    CITY = input("Enter city name: ")
    FILE_NAME = "weather_log.csv"

    log_weather(CITY, FILE_NAME, API_KEY)