# -*- coding: utf-8 -*-
"""Prime_Number_Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12RjuZdrM63FBGbHU0Runb5UnEudP2ej6
"""

def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False

    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6

    return True


try:
    # Take input
    start = int(input("Enter range start (positive integer): "))
    end = int(input("Enter range end (positive integer): "))

    # Validate input
    if start <= 0 or end <= 0:
        raise ValueError("Both numbers must be positive integers.")

    if start > end:
        raise ValueError("Start of range must be less than or equal to end.")

    # Find primes in range
    primes = [num for num in range(start, end + 1) if is_prime(num)]

    # Display formatted output
    if primes:
        print("\nPrime numbers in the given range:")
        for i, prime in enumerate(primes, 1):
            print(f"{prime:5}", end=" ")
            if i % 10 == 0:
                print()
        print()
    else:
        print("\nNo prime numbers found in the given range.")

except ValueError as ve:
    # Handle invalid input
    print(f"\n❌ Input Error: {ve}")

except Exception as e:
    # Catch any unexpected errors
    print("\n❌ An unexpected error occurred.")
    print(f"Details: {e}")