# -*- coding: utf-8 -*-
"""Student_Marks_Processor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14K-DEeeG6ocD1bB3vdCYnYIVxSWnskTO
"""

import numpy as np

INPUT_FILE = "student_marks.txt"
OUTPUT_FILE = "student_results.txt"

EXAM_WEIGHT = 0.7
COURSEWORK_WEIGHT = 0.3


def calculate_grade(overall):
    if overall >= 85:
        return 'A'
    elif overall >= 70:
        return 'B'
    elif overall >= 55:
        return 'C'
    elif overall >= 40:
        return 'D'
    else:
        return 'F'


try:
    records = []

    # Read student marks from file
    with open(INPUT_FILE, 'r') as file:
        for line_num, line in enumerate(file, start=1):
            try:
                reg_no, exam, coursework = line.strip().split(',')
                exam = float(exam)
                coursework = float(coursework)

                if not (0 <= exam <= 100 and 0 <= coursework <= 100):
                    raise ValueError("Marks must be between 0 and 100")

                # Compute overall mark
                overall = (exam * EXAM_WEIGHT) + (coursework * COURSEWORK_WEIGHT)

                # Assign grade
                grade = calculate_grade(overall)

                records.append((reg_no, exam, coursework, overall, grade))

            except ValueError as ve:
                print(f"⚠ Skipping invalid record on line {line_num}: {ve}")

    if not records:
        raise RuntimeError("No valid student records found.")

    # Create structured NumPy array
    dtype = [
        ('reg_no', 'U20'),
        ('exam', 'f4'),
        ('coursework', 'f4'),
        ('overall', 'f4'),
        ('grade', 'U1')
    ]

    students = np.array(records, dtype=dtype)

    # Sort by overall mark (descending)
    students_sorted = np.sort(students, order='overall')[::-1]

    # Write results to output file
    with open(OUTPUT_FILE, 'w') as file:
        file.write("Reg_No,Exam,Coursework,Overall,Grade\n")
        for s in students_sorted:
            file.write(
                f"{s['reg_no']},{s['exam']:.1f},{s['coursework']:.1f},"
                f"{s['overall']:.2f},{s['grade']}\n"
            )

    # Display grade statistics
    grades, counts = np.unique(students_sorted['grade'], return_counts=True)

    print("\nGrade Statistics:")
    for grade, count in zip(grades, counts):
        print(f"Grade {grade}: {count} student(s)")

    print(f"\nResults successfully written to '{OUTPUT_FILE}'")

except FileNotFoundError:
    print(f"❌ Error: Input file '{INPUT_FILE}' not found.")

except PermissionError:
    print("❌ Error: Permission denied while accessing files.")

except Exception as e:
    print("❌ An unexpected error occurred.")
    print(f"Details: {e}")